import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';
import './index.css';

// Register PWA service worker (generated by vite-plugin-pwa / Workbox)
// The virtual module 'virtual:pwa-register' is provided at build time.
// It is a no-op in dev unless devOptions.enabled = true in vite.config.js.
import { registerSW } from 'virtual:pwa-register';

registerSW({
  // Called when a new SW version is available and waiting.
  // autoUpdate (registerType: 'autoUpdate') handles this automatically,
  // but we hook in here to log / show a toast if desired.
  onRegisteredSW(swUrl, r) {
    if (import.meta.env.DEV) {
      console.log('[PWA] Service worker registered:', swUrl);
    }
    // Poll for updates every hour while the app is open
    if (r) {
      setInterval(() => r.update(), 60 * 60 * 1000);
    }
  },
  onOfflineReady() {
    if (import.meta.env.DEV) {
      console.log('[PWA] App ready to work offline');
    }
  },
});

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
